# Configtx.yaml is used to generate genesis block: orderer.genesis.block
# It contains all the organizations' info, including Name, ID, MSPDir and Anchor Peer's info
# And it also contains orderer's info including orderertype(solo), address, batchtimeout, batchsize and kafka info(if use solo, kafka info is invalid)

# Organizations tag includes all four organizations' info. There are ANZ, Citi Bank, Orderer and Supervisor
# All the Ahchor peers use peer0 and port 7051
Organizations:
    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: /opt/hyperledger/gopenbanking/crypto-config/ordererOrganizations/italktoyou.cn/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"

    - &ANZBank
        Name: ANZBank
        ID: ANZBankMSP
        MSPDir: /opt/hyperledger/gopenbanking/crypto-config/peerOrganizations/anz.italktoyou.cn/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('ANZBankMSP.admin', 'ANZBankMSP.peer', 'ANZBankMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('ANZBankMSP.admin', 'ANZBankMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('ANZBankMSP.admin')"
        AnchorPeers:
            - Host: peer0.anz.italktoyou.cn
              Port: 7051

    - &CitiBank
        Name: CitiBank
        ID: CitiBankMSP
        MSPDir: /opt/hyperledger/gopenbanking/crypto-config/peerOrganizations/citi.italktoyou.cn/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('CitiBankMSP.admin', 'ANZBankMSP.peer', 'ANZBankMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('CitiBankMSP.admin', 'ANZBankMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('CitiBankMSP.admin')"
        AnchorPeers:
            - Host: peer0.citi.italktoyou.cn
              Port: 7051

    - &Supervisor
        Name: Supervisor
        ID: SuperMSP
        MSPDir: /opt/hyperledger/gopenbanking/crypto-config/peerOrganizations/supervi.italktoyou.cn/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('SuperMSP.admin', 'SuperMSP.peer', 'SuperMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('SuperMSP.admin', 'SuperMSP.client')"
            Admins: 
                Type: Signature
                Rule: "OR('SuperMSP.admin')"
        AnchorPeers:
            - Host: peer0.supervi.italktoyou.cn
              Port: 7051

# Orderer tag includes specific information about orderer default settings
Orderer: &OrdererDefaults
    
    OrdererType: solo
    Addresses: 
        - orderer.italktoyou.cn
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 98 MB
        PreferredMaxBytes: 512 KB
    Kafka:
        Brokers:
            - 127.0.0.1:9092
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers: 
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers: 
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

Profiles:
    OrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            BankConsortium:
                Organizations:
                    - *ANZBank
                    - *CitiBank
                    - *Supervisor
    OrgsChannel:
        <<: *ChannelDefaults
        Consortium: BankConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *ANZBank
                - *CitiBank
                - *Supervisor
