logging:
    peer: debug
    cauthdsl: warning
    gossip: warning
    ledger: info
    msp: warning
    policies: warning
    grpc: error
    format: '%{color}%{time:2006-01-02 15:04:05.000 MST} [%{module}] %{shortfunc} -> %{level:.4s} %{id:03x}%{color:reset} %{message}'

peer:
    id: peer0.anz.italktoyou.cn
    networkId: dev
    listenAddress: 0.0.0.0:7051
    chaincodeListenAddress: 0.0.0.0:7052
    address: peer0.anz.italktoyou.cn:7051
    addressAutoDetect: false
    gomaxprocs: -1
    keepalive:
        minInterval: 60s
        client:
            interval: 60s
            timeout: 60s
        deliveryClient:
            interval: 60s
            timeout: 20s

    gossip:
        bootstrap: peer0.anz.italktoyou.cn:7051
        useledgerElection: true
        orgLeader: false
        membershipTrackerInterval: 5s
        endpoint:
        maxBlockCountToStore: 100
        maxPropagationBurstLatency: 10ms
        maxPropagationBurstSize: 10
        propagateIterations: 1
        propagatePeerNum: 3
        pullInterval: 3
        pullPeerNum: 3
        requestStateInfoInterval: 4s
        publishStateInfoInterval: 4s
        stateInfoRetentionInterval:
        publishCertPeriod: 10s
        skipBlockVerification: false
        dialTimeout: 3s
        connTimeout: 2s
        digestWaitTime: 1s
        requestWaitTime: 1500ms
        responseWaitTime: 2s
        aliveTimeInterval: 5s
        aliveExpirationTimeout: 25s
        reconnectInterval: 25s
        externalEndpoint: peer0.anz.italktoyou.cn:7051
        election:
            startUpGracePeriod: 15s
            membershipSampleInterval: 1s
            leaderAliveThreshold: 10s
            leaderElectionDuration: 5s
        pvtData:
            pullRetryThreshold: 60s
            transientstoreMaxBlockRetention: 1000
            pushAckTimeout: 3s
            btlPullMargin: 10
            reconcileBatchSize: 10
            reconcileSleepInterval: 1m
            skipPullingInvalidTransactionDruingCommit: false
        state:
            enabled: true
            checkInterval: 10s
            responseTimeout: 3s
            batchSize: 10
            blockBufferSize: 100
            maxRetries: 3
    tls:
        enabled: false
        clientAuthRequired: false
        cert: 
            file: /opt/hyperledger/gopenbanking/crypto-config/peerOrganizations/anz.italktoyou.cn/peers/peer0.anz.italktoyou.cn/tls/server.crt
        key: 
            file: /opt/hyperledger/gopenbanking/crypto-config/peerOrganizations/anz.italktoyou.cn/peers/peer0.anz.italktoyou.cn/tls/server.key
        rootcert:
            file: /opt/hyperledger/gopenbanking/crypto-config/peerOrganizations/anz.italktoyou.cn/peers/peer0.anz.italktoyou.cn/tls/ca.crt
        clientRootCAs:
            files:
              - tls/ca.crt
        clientKey:
            file:
        clientCert:
            file:
    authentication:
        timewindow: 15m
    fileSystemPath: /opt/hyperledger/gopenbanking/production
    BCCSP:
        Default: SW
        SW:
            Hash: SHA2
            Security: 256
            FileKeyStore:
                KeyStore:
        PKCS11:
            Library:
            Label:
            Pin:
            Hash:
            Security:
            FileKeyStore:
                KeyStore:
    mspConfigPath: /opt/hyperledger/gopenbanking/crypto-config/peerOrganizations/anz.italktoyou.cn/peers/peer0.anz.italktoyou.cn/msp
    localMspId: ANZBankMSP
    client:
        connTimetout: 3s
    deliveryclient:
        reconnectTotalTimeThreshold: 3600s
        connTimeout: 3s
        reConnectBackoffThreshold: 3600s
    localMspType: bccsp
    profile:
        enabled: false
        listenAddress: 0.0.0.0:7070
    adminService:
    handlers:
        authFilters:
          -
            name: DefaultAuth
          -
            name: ExpirationCheck
        decorators:
          -
            name: DefaultDecorator
        endorsers:
          escc:
            name: DefaultEndorsement
            library:
        validators:
          vscc:
            name: DefaultValidation
            library:
    validatorPoolSize:
    discovery:
        enabled: true
        authCacheEnabled: true
        authCacheMaxSize: 1000
        aurthCachePurgeRetentionRatio: 0.75
        orgMembersAllowedAccess: false

vm: 
    endpoint: unix://var/run/docker.sock
    docker:
        tls:
            enabled: false
            ca:
                file: docker/ca.crt
            cert:
                file: docker/tls.crt
            key:
                file: docker/tls.key
        attachStdout: false
        hostConfig:
            NetworkMode: host
            Dns:
            LogConfig:
                Type: json-file
                Config:
                    max-size: "50m"
                    max-file: "5"
            Memory: 2147483648

chaincode:
    id:
        path:
        name:
    builder: $(DOCKER_NS)/fabric-ccenv:latest
    pull: true
    golang: 
        runtime: $(BASE_DOCKER_NS)/fabric-baseos:$(ARCH_-$(BASE_VERSION)
        dynamicLink: false
    car:
        runtime: $(BASE_DOCKER_NS)/fabric-baseos:$(ARCH)-$(BASE_VERSION)
    java:
        runtime: $(DOCKER_NS)/fabric-javaenv:$(ARCH)-$(PROJECT_VERSION)
    node:
        runtime: $(BASE_DOCKER_NS)/fabric-baseimage:$(ARCH)-$(BASE_VERSION)
    startuptimeout: 300s
    executetimeout: 30s
    mode: net
    keepaive: 0
    system:
        cscc: enable
        lscc: enable
        escc: enable
        vscc: enable
        qscc: enable
    systemPlugins:
    logging:
        level: info
        shim: warning
        foramt: '%{color}%{time:2006-01-02 15:04:05.000 MST} [%{module}] %{shortfunc} -> %{level:.4s} %{id:03x}%{color:reset} %{message}'

ledger:
    blockchain:
    state:
        stateDatabase: goleveldb
        totalQueryLimit: 100000
        couchDBConfig:
            couchDBAddress: 127.0.0.1:5984
        username: 
        password:
        maxRetries: 3
        maxRetriesOnStartup: 12
        requestTimeout: 35s
        internalQueryLimit: 1000
        maxBatchUpdateSize: 1000
        warmIndexesafterNBlocks: 1
        createGlobalChangeDB: false
    history:
        enableHistoryDatabase: true

operations:
    listenAddress: 127.0.0.1:9443
    tls:
        enabled: false
        cert:
            file:
        key:
            file:
        clientAuthRequired: false
        clientRootCAs:
            files: []

metrics: 
    provider: disabled
    statsd:
        network: udp
        address: 127.0.0.1:8125
        writeInterval: 10s
        prefix:
